name: ci-tests
on:
  pull_request:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'  # nightly

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [ '3.10' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      # Smoke rápido en Pull Requests
      - name: Run smoke (PR)
        if: github.event_name == 'pull_request'
        run: |
          pytest -m smoke -q --junitxml=reports/junit_smoke.xml
          pytest -m kike -q --junitxml=reports/junit_kike.xml

      # Suite completa en main/nightly
      - name: Run full suite (main/nightly)
        if: github.event_name != 'pull_request'
        run: |
          pytest -q --junitxml=reports/junit_full.xml

      - name: Upload artifacts (reports)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/**
